### ISSUE TITLE
SSR?

### ISSUE THREAD

**Issue by neopostmodern** [aadamsx/fine-router#1]
Does this project aim at providing SSR support as FlowRouter [kind of] did in their `ssr` branch? It had very serious flaws there so I was wondering if they might be fixed here or if that is considered out of scope.

**Comment by aadamsx** [comment]
Hi @neopostmodern.  I saw that SSR branch and was going to have a look at what changes he made.  As you said it is not fully baked.  At the moment I do not use SSR (but might need this in the future), so I won't be spending too much time trying on it.

If you or someone else is interested, I can create a SSR branch here, and will accept PRs into it or I can assign anyone a contributor role and they can build SSR on that branch themselves to be integrated back into the main branch at some point.

Let me know if you have any other questions.

**Comment by neopostmodern** [comment]
Okay, there's at least one weird bug I'd like to fix, so if you'd create an SSR branch I'd write a PR for that, but I can't promise to dedicate much time to it overall.
