### ISSUE TITLE
Commit history

### ISSUE THREAD

**Issue by ramijarrar** [aadamsx/fine-router#2]
Was it an intentional decision not to migrate this over?

**Comment by aadamsx** [comment]
Sorry I don't follow.

**Comment by ramijarrar** [comment]
None of the commit history was retained from the original repo. This is fairly simple to migrate over, so the issue is concerning whether that is a desirable decision.

**Comment by aadamsx** [comment]
I didn't think it made a difference -- but if you do, please state why.  We should consider it if it makes sense for some reason.

**Comment by ramijarrar** [comment]
The difference is that you are losing valuable data about the history of the project which would otherwise aid our understanding of many code-related decisions and frankly undermine the work of those (38 people as it stands) that contributed to the original repo. 

Besides, there is existing work on feature branches and more than 80 release tags which would be thrown away unnecessarily.

I would say either:

1) Fork the project and detach from the original repo
2) Clone and add the new repo as a remote (a little more involved)

**Comment by aadamsx** [comment]
> valuable data about the history of the project which would otherwise aid our understanding of many code-related decisions

Explain this more.  What understanding do you think we need?  What code-related decisions do you think are valuable?

**Comment by ramijarrar** [comment]
These are pretty basic version control concepts,

Consider doing some external reading:

- http://programmers.stackexchange.com/questions/39287/preserving-version-control-commit-history-vs-refactoring-and-documentation
- http://www.bitsnbites.eu/?p=221
- http://megakemp.com/2014/08/14/the-importance-of-a-good-looking-history/

**Comment by aadamsx** [comment]
Sorry. I wasn't asking for version control basics. Thansks for your feedback.

**Comment by ramijarrar** [comment]
You were asking me to explain the value/potential applications of commit history.

Since this is pretty fundamental, it's easier for me to link to external articles that directly address this (e.g past stack exchange questions) rather than rehashing myself.

It was not my intention to offend you or detract from the overall effort of this project & I apologize if you interpreted it this way.

**Comment by ramijarrar** [comment]
Why did you delete my comments?

**Comment by ramijarrar** [comment]
I fully understand your motivations for starting FineRouter and the history of the project. At no point was my intention to offend you or detract from the overall effort (which is in everyone's best interests). The whole idea behind opening this issue was to contribute.

**Comment by aadamsx** [comment]
That's ok -- you don't sound stupid.  No -- I think the readme does justice to this repo.  The ONLY reason I forked this repo was so others could contribute -- as the original authors had abandoned the repo.  

If you'd like to contribute -- please let me know and I'll give you write access.

**Comment by AlexanderS** [comment]
I think @ramijarrar wanted to ask, if there is any reason why this is not a real fork (f.e. using the fork button of github) and does not contain the older commits? A big fat initial commit, dropping all the history isn't really good style.

**Comment by aadamsx** [comment]
Well, it's not that big a deal IMO.
